# Cloud Build configuration for automated deployment
steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/financial-analyst:$COMMIT_SHA', '.']
  
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/financial-analyst:$COMMIT_SHA']
  
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'financial-analyst'
      - '--image'
      - 'gcr.io/$PROJECT_ID/financial-analyst:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '8080'
      - '--memory'
      - '4Gi'
      - '--cpu'
      - '2'
      - '--max-instances'
      - '10'
      - '--min-instances'
      - '0'
      - '--set-env-vars'
      - 'STREAMLIT_SERVER_HEADLESS=true,STREAMLIT_BROWSER_GATHER_USAGE_STATS=false,TOKENIZERS_PARALLELISM=false'
      - '--set-secrets'
      - 'GOOGLE_AI_API_KEY=google-ai-api-key:latest'

# Also tag as latest
  - name: 'gcr.io/cloud-builders/docker'
    args: ['tag', 'gcr.io/$PROJECT_ID/financial-analyst:$COMMIT_SHA', 'gcr.io/$PROJECT_ID/financial-analyst:latest']
  
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/financial-analyst:latest']

# Optional: Keep some images for rollback
images:
  - 'gcr.io/$PROJECT_ID/financial-analyst:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/financial-analyst:latest'

# Cloud Build configuration
options:
  logging: CLOUD_LOGGING_ONLY
  
timeout: '1800s'  # 30 minutes for ML model downloads