apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: financial-advisor
  annotations:
    run.googleapis.com/ingress: all
    run.googleapis.com/execution-environment: gen2
spec:
  template:
    metadata:
      annotations:
        # Resource allocation
        run.googleapis.com/cpu: "2"
        run.googleapis.com/memory: "4Gi"
        run.googleapis.com/execution-environment: gen2
        # Startup and timeout settings
        run.googleapis.com/timeout: "300s"
        run.googleapis.com/cpu-throttling: "false"
        # Scaling settings
        autoscaling.knative.dev/minScale: "0"
        autoscaling.knative.dev/maxScale: "10"
    spec:
      containerConcurrency: 10
      timeoutSeconds: 300
      containers:
      - name: financial-advisor
        image: gcr.io/PROJECT_ID/financial-advisor:latest
        ports:
        - containerPort: 8080
          name: http1
        env:
        - name: GOOGLE_AI_API_KEY
          valueFrom:
            secretKeyRef:
              name: gemini-api-key
              key: api-key
        - name: STREAMLIT_SERVER_PORT
          value: "8080"
        - name: STREAMLIT_SERVER_ADDRESS
          value: "0.0.0.0"
        - name: STREAMLIT_SERVER_HEADLESS
          value: "true"
        - name: STREAMLIT_BROWSER_GATHER_USAGE_STATS
          value: "false"
        # ML/AI optimizations
        - name: TOKENIZERS_PARALLELISM
          value: "false"
        - name: TRANSFORMERS_CACHE
          value: "/app/.cache/transformers"
        - name: HF_HOME
          value: "/app/.cache/huggingface"
        # Resource limits and requests
        resources:
          requests:
            cpu: "1"
            memory: "2Gi"
          limits:
            cpu: "2"
            memory: "4Gi"
        # Health checks
        livenessProbe:
          httpGet:
            path: /_stcore/health
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            path: /_stcore/health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5